const CONFIG = {
  ALUGUEL: 100,
  ASSINATURAS_SOFTWARES: 100,
  PLATAFORMAS_ECOMMERCE: 0,
  TAXA_MEI: 0,
  PUBLICIDADE_MINIMA_FIXA: 100,
  AMORTIZACAO: 0,
  CONDOMINIO: 0,
  OUTROS_CUSTOS_FIXOS: 0,
  HORAS_PRODUTIVAS_MENSAIS: 360,

  TINTA_ACRILICA: 20,
  PRIMER: 20,
  VERNIZ: 20,
  CONSUMO_PINTURA_SIMPLES_PCT: 5,
  CONSUMO_PINTURA_MEDIA_PCT: 10,
  CONSUMO_PINTURA_COMPLEXA_PCT: 20,
  MAO_DE_OBRA_PINTURA_POR_HORA: 10,

  RISCO_FALHAS_PCT: 10,

  CUSTO_KWH: 0.88,
  VALOR_IMPRESSORA: 5000,
  VIDA_UTIL_IMPRESSORA_HORAS: 10000,
  POTENCIA_IMPRESSORA_W: 100,
  CONSUMIVEIS_POR_HORA: 0.50,

  PERCENTUAL_SHOPEE: 20,
  TAXA_FIXA_SHOPEE: 4,
  PERCENTUAL_MERCADO_LIVRE: 19,
};
